# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import pulumi
from enum import Enum

__all__ = [
    'Access',
    'ActionType',
    'AddressPrefixType',
    'AdminRuleKind',
    'AdminState',
    'ApplicationGatewayClientRevocationOptions',
    'ApplicationGatewayCookieBasedAffinity',
    'ApplicationGatewayCustomErrorStatusCode',
    'ApplicationGatewayFirewallMode',
    'ApplicationGatewayFirewallRateLimitDuration',
    'ApplicationGatewayFirewallUserSessionVariable',
    'ApplicationGatewayLoadDistributionAlgorithm',
    'ApplicationGatewayProtocol',
    'ApplicationGatewayRedirectType',
    'ApplicationGatewayRequestRoutingRuleType',
    'ApplicationGatewaySkuName',
    'ApplicationGatewaySslCipherSuite',
    'ApplicationGatewaySslPolicyName',
    'ApplicationGatewaySslPolicyType',
    'ApplicationGatewaySslProtocol',
    'ApplicationGatewayTier',
    'AuthorizationUseStatus',
    'AutoLearnPrivateRangesMode',
    'AzureFirewallApplicationRuleProtocolType',
    'AzureFirewallNatRCActionType',
    'AzureFirewallNetworkRuleProtocol',
    'AzureFirewallRCActionType',
    'AzureFirewallSkuName',
    'AzureFirewallSkuTier',
    'AzureFirewallThreatIntelMode',
    'BastionHostSkuName',
    'CommissionedState',
    'ConfigurationType',
    'ConnectionMonitorEndpointFilterItemType',
    'ConnectionMonitorEndpointFilterType',
    'ConnectionMonitorTestConfigurationProtocol',
    'ConnectivityTopology',
    'CoverageLevel',
    'CustomIpPrefixType',
    'DdosSettingsProtectionMode',
    'DeleteExistingPeering',
    'DeleteOptions',
    'DestinationPortBehavior',
    'DhGroup',
    'EndpointType',
    'ExpressRouteCircuitPeeringState',
    'ExpressRouteCircuitSkuFamily',
    'ExpressRouteCircuitSkuTier',
    'ExpressRouteLinkAdminState',
    'ExpressRouteLinkMacSecCipher',
    'ExpressRouteLinkMacSecSciState',
    'ExpressRoutePeeringState',
    'ExpressRoutePeeringType',
    'ExpressRoutePortsBillingType',
    'ExpressRoutePortsEncapsulation',
    'ExtendedLocationTypes',
    'FirewallPolicyFilterRuleCollectionActionType',
    'FirewallPolicyIDPSQuerySortOrder',
    'FirewallPolicyIntrusionDetectionProtocol',
    'FirewallPolicyIntrusionDetectionStateType',
    'FirewallPolicyNatRuleCollectionActionType',
    'FirewallPolicyRuleApplicationProtocolType',
    'FirewallPolicyRuleCollectionType',
    'FirewallPolicyRuleNetworkProtocol',
    'FirewallPolicyRuleType',
    'FirewallPolicySkuTier',
    'FlowLogFormatType',
    'GatewayLoadBalancerTunnelInterfaceType',
    'GatewayLoadBalancerTunnelProtocol',
    'Geo',
    'GroupConnectivity',
    'HTTPConfigurationMethod',
    'HubRoutingPreference',
    'IPAllocationMethod',
    'IPVersion',
    'IkeEncryption',
    'IkeIntegrity',
    'IpAllocationType',
    'IpsecEncryption',
    'IpsecIntegrity',
    'IsGlobal',
    'LoadBalancerBackendAddressAdminState',
    'LoadBalancerOutboundRuleProtocol',
    'LoadBalancerSkuName',
    'LoadBalancerSkuTier',
    'LoadDistribution',
    'ManagedRuleEnabledState',
    'NatGatewaySkuName',
    'NetworkIntentPolicyBasedService',
    'NetworkInterfaceAuxiliaryMode',
    'NetworkInterfaceAuxiliarySku',
    'NetworkInterfaceMigrationPhase',
    'NetworkInterfaceNicType',
    'NextStep',
    'OutputType',
    'OwaspCrsExclusionEntryMatchVariable',
    'OwaspCrsExclusionEntrySelectorMatchOperator',
    'PacketCaptureTargetType',
    'PcProtocol',
    'PfsGroup',
    'PreferredIPVersion',
    'PreferredRoutingGateway',
    'ProbeProtocol',
    'ProtocolType',
    'PublicIPAddressMigrationPhase',
    'PublicIPAddressSkuName',
    'PublicIPAddressSkuTier',
    'PublicIPPrefixSkuName',
    'PublicIPPrefixSkuTier',
    'PublicIpAddressDnsSettingsDomainNameLabelScope',
    'ResourceIdentityType',
    'RouteFilterRuleType',
    'RouteMapActionType',
    'RouteMapMatchCondition',
    'RouteNextHopType',
    'ScrubbingRuleEntryMatchOperator',
    'ScrubbingRuleEntryMatchVariable',
    'ScrubbingRuleEntryState',
    'SecurityConfigurationRuleAccess',
    'SecurityConfigurationRuleDirection',
    'SecurityConfigurationRuleProtocol',
    'SecurityProviderName',
    'SecurityRuleAccess',
    'SecurityRuleDirection',
    'SecurityRuleProtocol',
    'ServiceProviderProvisioningState',
    'TransportProtocol',
    'UseHubGateway',
    'VirtualNetworkEncryptionEnforcement',
    'VirtualNetworkGatewayConnectionMode',
    'VirtualNetworkGatewayConnectionProtocol',
    'VirtualNetworkGatewayConnectionType',
    'VirtualNetworkGatewaySkuName',
    'VirtualNetworkGatewaySkuTier',
    'VirtualNetworkGatewayType',
    'VirtualNetworkPeeringLevel',
    'VirtualNetworkPeeringState',
    'VirtualNetworkPrivateEndpointNetworkPolicies',
    'VirtualNetworkPrivateLinkServiceNetworkPolicies',
    'VnetLocalRouteOverrideCriteria',
    'VpnAuthenticationType',
    'VpnClientProtocol',
    'VpnGatewayGeneration',
    'VpnGatewayTunnelingProtocol',
    'VpnLinkConnectionMode',
    'VpnNatRuleMode',
    'VpnNatRuleType',
    'VpnPolicyMemberAttributeType',
    'VpnType',
    'WebApplicationFirewallAction',
    'WebApplicationFirewallEnabledState',
    'WebApplicationFirewallMatchVariable',
    'WebApplicationFirewallMode',
    'WebApplicationFirewallOperator',
    'WebApplicationFirewallRuleType',
    'WebApplicationFirewallScrubbingState',
    'WebApplicationFirewallState',
    'WebApplicationFirewallTransform',
]


@pulumi.type_token("azure-native_network_v20230201:network:Access")
class Access(builtins.str, Enum):
    """
    The access type of the rule.
    """
    ALLOW = "Allow"
    DENY = "Deny"


@pulumi.type_token("azure-native_network_v20230201:network:ActionType")
class ActionType(builtins.str, Enum):
    """
    Describes the override action to be applied when rule matches.
    """
    ANOMALY_SCORING = "AnomalyScoring"
    ALLOW = "Allow"
    BLOCK = "Block"
    LOG = "Log"


@pulumi.type_token("azure-native_network_v20230201:network:AddressPrefixType")
class AddressPrefixType(builtins.str, Enum):
    """
    Address prefix type.
    """
    IP_PREFIX = "IPPrefix"
    SERVICE_TAG = "ServiceTag"


@pulumi.type_token("azure-native_network_v20230201:network:AdminRuleKind")
class AdminRuleKind(builtins.str, Enum):
    """
    Whether the rule is custom or default.
    """
    CUSTOM = "Custom"
    DEFAULT = "Default"


@pulumi.type_token("azure-native_network_v20230201:network:AdminState")
class AdminState(builtins.str, Enum):
    """
    Property to indicate if the Express Route Gateway serves traffic when there are multiple Express Route Gateways in the vnet
    """
    ENABLED = "Enabled"
    DISABLED = "Disabled"


@pulumi.type_token("azure-native_network_v20230201:network:ApplicationGatewayClientRevocationOptions")
class ApplicationGatewayClientRevocationOptions(builtins.str, Enum):
    """
    Verify client certificate revocation status.
    """
    NONE = "None"
    OCSP = "OCSP"


@pulumi.type_token("azure-native_network_v20230201:network:ApplicationGatewayCookieBasedAffinity")
class ApplicationGatewayCookieBasedAffinity(builtins.str, Enum):
    """
    Cookie based affinity.
    """
    ENABLED = "Enabled"
    DISABLED = "Disabled"


@pulumi.type_token("azure-native_network_v20230201:network:ApplicationGatewayCustomErrorStatusCode")
class ApplicationGatewayCustomErrorStatusCode(builtins.str, Enum):
    """
    Status code of the application gateway custom error.
    """
    HTTP_STATUS400 = "HttpStatus400"
    HTTP_STATUS403 = "HttpStatus403"
    HTTP_STATUS404 = "HttpStatus404"
    HTTP_STATUS405 = "HttpStatus405"
    HTTP_STATUS408 = "HttpStatus408"
    HTTP_STATUS500 = "HttpStatus500"
    HTTP_STATUS502 = "HttpStatus502"
    HTTP_STATUS503 = "HttpStatus503"
    HTTP_STATUS504 = "HttpStatus504"


@pulumi.type_token("azure-native_network_v20230201:network:ApplicationGatewayFirewallMode")
class ApplicationGatewayFirewallMode(builtins.str, Enum):
    """
    Web application firewall mode.
    """
    DETECTION = "Detection"
    PREVENTION = "Prevention"


@pulumi.type_token("azure-native_network_v20230201:network:ApplicationGatewayFirewallRateLimitDuration")
class ApplicationGatewayFirewallRateLimitDuration(builtins.str, Enum):
    """
    Duration over which Rate Limit policy will be applied. Applies only when ruleType is RateLimitRule.
    """
    ONE_MIN = "OneMin"
    FIVE_MINS = "FiveMins"


@pulumi.type_token("azure-native_network_v20230201:network:ApplicationGatewayFirewallUserSessionVariable")
class ApplicationGatewayFirewallUserSessionVariable(builtins.str, Enum):
    """
    User Session clause variable.
    """
    CLIENT_ADDR = "ClientAddr"
    GEO_LOCATION = "GeoLocation"
    NONE = "None"


@pulumi.type_token("azure-native_network_v20230201:network:ApplicationGatewayLoadDistributionAlgorithm")
class ApplicationGatewayLoadDistributionAlgorithm(builtins.str, Enum):
    """
    Load Distribution Targets resource of an application gateway.
    """
    ROUND_ROBIN = "RoundRobin"
    LEAST_CONNECTIONS = "LeastConnections"
    IP_HASH = "IpHash"


@pulumi.type_token("azure-native_network_v20230201:network:ApplicationGatewayProtocol")
class ApplicationGatewayProtocol(builtins.str, Enum):
    """
    The protocol used for the probe.
    """
    HTTP = "Http"
    HTTPS = "Https"
    TCP = "Tcp"
    TLS = "Tls"


@pulumi.type_token("azure-native_network_v20230201:network:ApplicationGatewayRedirectType")
class ApplicationGatewayRedirectType(builtins.str, Enum):
    """
    HTTP redirection type.
    """
    PERMANENT = "Permanent"
    FOUND = "Found"
    SEE_OTHER = "SeeOther"
    TEMPORARY = "Temporary"


@pulumi.type_token("azure-native_network_v20230201:network:ApplicationGatewayRequestRoutingRuleType")
class ApplicationGatewayRequestRoutingRuleType(builtins.str, Enum):
    """
    Rule type.
    """
    BASIC = "Basic"
    PATH_BASED_ROUTING = "PathBasedRouting"


@pulumi.type_token("azure-native_network_v20230201:network:ApplicationGatewaySkuName")
class ApplicationGatewaySkuName(builtins.str, Enum):
    """
    Name of an application gateway SKU.
    """
    STANDARD_SMALL = "Standard_Small"
    STANDARD_MEDIUM = "Standard_Medium"
    STANDARD_LARGE = "Standard_Large"
    WA_F_MEDIUM = "WAF_Medium"
    WA_F_LARGE = "WAF_Large"
    STANDARD_V2 = "Standard_v2"
    WA_F_V2 = "WAF_v2"


@pulumi.type_token("azure-native_network_v20230201:network:ApplicationGatewaySslCipherSuite")
class ApplicationGatewaySslCipherSuite(builtins.str, Enum):
    """
    Ssl cipher suites enums.
    """
    TL_S_ECDH_E_RS_A_WIT_H_AE_S_256_CB_C_SHA384 = "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384"
    TL_S_ECDH_E_RS_A_WIT_H_AE_S_128_CB_C_SHA256 = "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256"
    TL_S_ECDH_E_RS_A_WIT_H_AE_S_256_CB_C_SHA = "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA"
    TL_S_ECDH_E_RS_A_WIT_H_AE_S_128_CB_C_SHA = "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA"
    TL_S_DH_E_RS_A_WIT_H_AE_S_256_GC_M_SHA384 = "TLS_DHE_RSA_WITH_AES_256_GCM_SHA384"
    TL_S_DH_E_RS_A_WIT_H_AE_S_128_GC_M_SHA256 = "TLS_DHE_RSA_WITH_AES_128_GCM_SHA256"
    TL_S_DH_E_RS_A_WIT_H_AE_S_256_CB_C_SHA = "TLS_DHE_RSA_WITH_AES_256_CBC_SHA"
    TL_S_DH_E_RS_A_WIT_H_AE_S_128_CB_C_SHA = "TLS_DHE_RSA_WITH_AES_128_CBC_SHA"
    TL_S_RS_A_WIT_H_AE_S_256_GC_M_SHA384 = "TLS_RSA_WITH_AES_256_GCM_SHA384"
    TL_S_RS_A_WIT_H_AE_S_128_GC_M_SHA256 = "TLS_RSA_WITH_AES_128_GCM_SHA256"
    TL_S_RS_A_WIT_H_AE_S_256_CB_C_SHA256 = "TLS_RSA_WITH_AES_256_CBC_SHA256"
    TL_S_RS_A_WIT_H_AE_S_128_CB_C_SHA256 = "TLS_RSA_WITH_AES_128_CBC_SHA256"
    TL_S_RS_A_WIT_H_AE_S_256_CB_C_SHA = "TLS_RSA_WITH_AES_256_CBC_SHA"
    TL_S_RS_A_WIT_H_AE_S_128_CB_C_SHA = "TLS_RSA_WITH_AES_128_CBC_SHA"
    TL_S_ECDH_E_ECDS_A_WIT_H_AE_S_256_GC_M_SHA384 = "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
    TL_S_ECDH_E_ECDS_A_WIT_H_AE_S_128_GC_M_SHA256 = "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
    TL_S_ECDH_E_ECDS_A_WIT_H_AE_S_256_CB_C_SHA384 = "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384"
    TL_S_ECDH_E_ECDS_A_WIT_H_AE_S_128_CB_C_SHA256 = "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256"
    TL_S_ECDH_E_ECDS_A_WIT_H_AE_S_256_CB_C_SHA = "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA"
    TL_S_ECDH_E_ECDS_A_WIT_H_AE_S_128_CB_C_SHA = "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA"
    TL_S_DH_E_DS_S_WIT_H_AE_S_256_CB_C_SHA256 = "TLS_DHE_DSS_WITH_AES_256_CBC_SHA256"
    TL_S_DH_E_DS_S_WIT_H_AE_S_128_CB_C_SHA256 = "TLS_DHE_DSS_WITH_AES_128_CBC_SHA256"
    TL_S_DH_E_DS_S_WIT_H_AE_S_256_CB_C_SHA = "TLS_DHE_DSS_WITH_AES_256_CBC_SHA"
    TL_S_DH_E_DS_S_WIT_H_AE_S_128_CB_C_SHA = "TLS_DHE_DSS_WITH_AES_128_CBC_SHA"
    TL_S_RS_A_WIT_H_3_DE_S_ED_E_CB_C_SHA = "TLS_RSA_WITH_3DES_EDE_CBC_SHA"
    TL_S_DH_E_DS_S_WIT_H_3_DE_S_ED_E_CB_C_SHA = "TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA"
    TL_S_ECDH_E_RS_A_WIT_H_AE_S_128_GC_M_SHA256 = "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
    TL_S_ECDH_E_RS_A_WIT_H_AE_S_256_GC_M_SHA384 = "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"


@pulumi.type_token("azure-native_network_v20230201:network:ApplicationGatewaySslPolicyName")
class ApplicationGatewaySslPolicyName(builtins.str, Enum):
    """
    Name of Ssl predefined policy.
    """
    APP_GW_SSL_POLICY20150501 = "AppGwSslPolicy20150501"
    APP_GW_SSL_POLICY20170401 = "AppGwSslPolicy20170401"
    APP_GW_SSL_POLICY20170401_S = "AppGwSslPolicy20170401S"
    APP_GW_SSL_POLICY20220101 = "AppGwSslPolicy20220101"
    APP_GW_SSL_POLICY20220101_S = "AppGwSslPolicy20220101S"


@pulumi.type_token("azure-native_network_v20230201:network:ApplicationGatewaySslPolicyType")
class ApplicationGatewaySslPolicyType(builtins.str, Enum):
    """
    Type of Ssl Policy.
    """
    PREDEFINED = "Predefined"
    CUSTOM = "Custom"
    CUSTOM_V2 = "CustomV2"


@pulumi.type_token("azure-native_network_v20230201:network:ApplicationGatewaySslProtocol")
class ApplicationGatewaySslProtocol(builtins.str, Enum):
    """
    Minimum version of Ssl protocol to be supported on application gateway.
    """
    TL_SV1_0 = "TLSv1_0"
    TL_SV1_1 = "TLSv1_1"
    TL_SV1_2 = "TLSv1_2"
    TL_SV1_3 = "TLSv1_3"


@pulumi.type_token("azure-native_network_v20230201:network:ApplicationGatewayTier")
class ApplicationGatewayTier(builtins.str, Enum):
    """
    Tier of an application gateway.
    """
    STANDARD = "Standard"
    WAF = "WAF"
    STANDARD_V2 = "Standard_v2"
    WA_F_V2 = "WAF_v2"


@pulumi.type_token("azure-native_network_v20230201:network:AuthorizationUseStatus")
class AuthorizationUseStatus(builtins.str, Enum):
    """
    The authorization use status.
    """
    AVAILABLE = "Available"
    IN_USE = "InUse"


@pulumi.type_token("azure-native_network_v20230201:network:AutoLearnPrivateRangesMode")
class AutoLearnPrivateRangesMode(builtins.str, Enum):
    """
    The operation mode for automatically learning private ranges to not be SNAT
    """
    ENABLED = "Enabled"
    DISABLED = "Disabled"


@pulumi.type_token("azure-native_network_v20230201:network:AzureFirewallApplicationRuleProtocolType")
class AzureFirewallApplicationRuleProtocolType(builtins.str, Enum):
    """
    Protocol type.
    """
    HTTP = "Http"
    HTTPS = "Https"
    MSSQL = "Mssql"


@pulumi.type_token("azure-native_network_v20230201:network:AzureFirewallNatRCActionType")
class AzureFirewallNatRCActionType(builtins.str, Enum):
    """
    The type of action.
    """
    SNAT = "Snat"
    DNAT = "Dnat"


@pulumi.type_token("azure-native_network_v20230201:network:AzureFirewallNetworkRuleProtocol")
class AzureFirewallNetworkRuleProtocol(builtins.str, Enum):
    """
    The protocol of a Network Rule resource.
    """
    TCP = "TCP"
    UDP = "UDP"
    ANY = "Any"
    ICMP = "ICMP"


@pulumi.type_token("azure-native_network_v20230201:network:AzureFirewallRCActionType")
class AzureFirewallRCActionType(builtins.str, Enum):
    """
    The type of action.
    """
    ALLOW = "Allow"
    DENY = "Deny"


@pulumi.type_token("azure-native_network_v20230201:network:AzureFirewallSkuName")
class AzureFirewallSkuName(builtins.str, Enum):
    """
    Name of an Azure Firewall SKU.
    """
    AZF_W_V_NET = "AZFW_VNet"
    AZF_W_HUB = "AZFW_Hub"


@pulumi.type_token("azure-native_network_v20230201:network:AzureFirewallSkuTier")
class AzureFirewallSkuTier(builtins.str, Enum):
    """
    Tier of an Azure Firewall.
    """
    STANDARD = "Standard"
    PREMIUM = "Premium"
    BASIC = "Basic"


@pulumi.type_token("azure-native_network_v20230201:network:AzureFirewallThreatIntelMode")
class AzureFirewallThreatIntelMode(builtins.str, Enum):
    """
    The operation mode for Threat Intelligence.
    """
    ALERT = "Alert"
    DENY = "Deny"
    OFF = "Off"


@pulumi.type_token("azure-native_network_v20230201:network:BastionHostSkuName")
class BastionHostSkuName(builtins.str, Enum):
    """
    The name of this Bastion Host.
    """
    BASIC = "Basic"
    STANDARD = "Standard"


@pulumi.type_token("azure-native_network_v20230201:network:CommissionedState")
class CommissionedState(builtins.str, Enum):
    """
    The commissioned state of the Custom IP Prefix.
    """
    PROVISIONING = "Provisioning"
    PROVISIONED = "Provisioned"
    COMMISSIONING = "Commissioning"
    COMMISSIONED_NO_INTERNET_ADVERTISE = "CommissionedNoInternetAdvertise"
    COMMISSIONED = "Commissioned"
    DECOMMISSIONING = "Decommissioning"
    DEPROVISIONING = "Deprovisioning"
    DEPROVISIONED = "Deprovisioned"


@pulumi.type_token("azure-native_network_v20230201:network:ConfigurationType")
class ConfigurationType(builtins.str, Enum):
    """
    Configuration Deployment Type.
    """
    SECURITY_ADMIN = "SecurityAdmin"
    CONNECTIVITY = "Connectivity"


@pulumi.type_token("azure-native_network_v20230201:network:ConnectionMonitorEndpointFilterItemType")
class ConnectionMonitorEndpointFilterItemType(builtins.str, Enum):
    """
    The type of item included in the filter. Currently only 'AgentAddress' is supported.
    """
    AGENT_ADDRESS = "AgentAddress"


@pulumi.type_token("azure-native_network_v20230201:network:ConnectionMonitorEndpointFilterType")
class ConnectionMonitorEndpointFilterType(builtins.str, Enum):
    """
    The behavior of the endpoint filter. Currently only 'Include' is supported.
    """
    INCLUDE = "Include"


@pulumi.type_token("azure-native_network_v20230201:network:ConnectionMonitorTestConfigurationProtocol")
class ConnectionMonitorTestConfigurationProtocol(builtins.str, Enum):
    """
    The protocol to use in test evaluation.
    """
    TCP = "Tcp"
    HTTP = "Http"
    ICMP = "Icmp"


@pulumi.type_token("azure-native_network_v20230201:network:ConnectivityTopology")
class ConnectivityTopology(builtins.str, Enum):
    """
    Connectivity topology type.
    """
    HUB_AND_SPOKE = "HubAndSpoke"
    MESH = "Mesh"


@pulumi.type_token("azure-native_network_v20230201:network:CoverageLevel")
class CoverageLevel(builtins.str, Enum):
    """
    Test coverage for the endpoint.
    """
    DEFAULT = "Default"
    LOW = "Low"
    BELOW_AVERAGE = "BelowAverage"
    AVERAGE = "Average"
    ABOVE_AVERAGE = "AboveAverage"
    FULL = "Full"


@pulumi.type_token("azure-native_network_v20230201:network:CustomIpPrefixType")
class CustomIpPrefixType(builtins.str, Enum):
    """
    Type of custom IP prefix. Should be Singular, Parent, or Child.
    """
    SINGULAR = "Singular"
    PARENT = "Parent"
    CHILD = "Child"


@pulumi.type_token("azure-native_network_v20230201:network:DdosSettingsProtectionMode")
class DdosSettingsProtectionMode(builtins.str, Enum):
    """
    The DDoS protection mode of the public IP
    """
    VIRTUAL_NETWORK_INHERITED = "VirtualNetworkInherited"
    ENABLED = "Enabled"
    DISABLED = "Disabled"


@pulumi.type_token("azure-native_network_v20230201:network:DeleteExistingPeering")
class DeleteExistingPeering(builtins.str, Enum):
    """
    Flag if need to remove current existing peerings.
    """
    FALSE = "False"
    TRUE = "True"


@pulumi.type_token("azure-native_network_v20230201:network:DeleteOptions")
class DeleteOptions(builtins.str, Enum):
    """
    Specify what happens to the public IP address when the VM using it is deleted
    """
    DELETE = "Delete"
    DETACH = "Detach"


@pulumi.type_token("azure-native_network_v20230201:network:DestinationPortBehavior")
class DestinationPortBehavior(builtins.str, Enum):
    """
    Destination port behavior.
    """
    NONE = "None"
    LISTEN_IF_AVAILABLE = "ListenIfAvailable"


@pulumi.type_token("azure-native_network_v20230201:network:DhGroup")
class DhGroup(builtins.str, Enum):
    """
    The DH Group used in IKE Phase 1 for initial SA.
    """
    NONE = "None"
    DH_GROUP1 = "DHGroup1"
    DH_GROUP2 = "DHGroup2"
    DH_GROUP14 = "DHGroup14"
    DH_GROUP2048 = "DHGroup2048"
    ECP256 = "ECP256"
    ECP384 = "ECP384"
    DH_GROUP24 = "DHGroup24"


@pulumi.type_token("azure-native_network_v20230201:network:EndpointType")
class EndpointType(builtins.str, Enum):
    """
    The endpoint type.
    """
    AZURE_VM = "AzureVM"
    AZURE_V_NET = "AzureVNet"
    AZURE_SUBNET = "AzureSubnet"
    EXTERNAL_ADDRESS = "ExternalAddress"
    MMA_WORKSPACE_MACHINE = "MMAWorkspaceMachine"
    MMA_WORKSPACE_NETWORK = "MMAWorkspaceNetwork"
    AZURE_ARC_VM = "AzureArcVM"
    AZURE_VMSS = "AzureVMSS"


@pulumi.type_token("azure-native_network_v20230201:network:ExpressRouteCircuitPeeringState")
class ExpressRouteCircuitPeeringState(builtins.str, Enum):
    """
    The state of peering.
    """
    DISABLED = "Disabled"
    ENABLED = "Enabled"


@pulumi.type_token("azure-native_network_v20230201:network:ExpressRouteCircuitSkuFamily")
class ExpressRouteCircuitSkuFamily(builtins.str, Enum):
    """
    The family of the SKU.
    """
    UNLIMITED_DATA = "UnlimitedData"
    METERED_DATA = "MeteredData"


@pulumi.type_token("azure-native_network_v20230201:network:ExpressRouteCircuitSkuTier")
class ExpressRouteCircuitSkuTier(builtins.str, Enum):
    """
    The tier of the SKU.
    """
    STANDARD = "Standard"
    PREMIUM = "Premium"
    BASIC = "Basic"
    LOCAL = "Local"


@pulumi.type_token("azure-native_network_v20230201:network:ExpressRouteLinkAdminState")
class ExpressRouteLinkAdminState(builtins.str, Enum):
    """
    Administrative state of the physical port.
    """
    ENABLED = "Enabled"
    DISABLED = "Disabled"


@pulumi.type_token("azure-native_network_v20230201:network:ExpressRouteLinkMacSecCipher")
class ExpressRouteLinkMacSecCipher(builtins.str, Enum):
    """
    Mac security cipher.
    """
    GCM_AES256 = "GcmAes256"
    GCM_AES128 = "GcmAes128"
    GCM_AES_XPN128 = "GcmAesXpn128"
    GCM_AES_XPN256 = "GcmAesXpn256"


@pulumi.type_token("azure-native_network_v20230201:network:ExpressRouteLinkMacSecSciState")
class ExpressRouteLinkMacSecSciState(builtins.str, Enum):
    """
    Sci mode enabled/disabled.
    """
    DISABLED = "Disabled"
    ENABLED = "Enabled"


@pulumi.type_token("azure-native_network_v20230201:network:ExpressRoutePeeringState")
class ExpressRoutePeeringState(builtins.str, Enum):
    """
    The peering state.
    """
    DISABLED = "Disabled"
    ENABLED = "Enabled"


@pulumi.type_token("azure-native_network_v20230201:network:ExpressRoutePeeringType")
class ExpressRoutePeeringType(builtins.str, Enum):
    """
    The peering type.
    """
    AZURE_PUBLIC_PEERING = "AzurePublicPeering"
    AZURE_PRIVATE_PEERING = "AzurePrivatePeering"
    MICROSOFT_PEERING = "MicrosoftPeering"


@pulumi.type_token("azure-native_network_v20230201:network:ExpressRoutePortsBillingType")
class ExpressRoutePortsBillingType(builtins.str, Enum):
    """
    The billing type of the ExpressRoutePort resource.
    """
    METERED_DATA = "MeteredData"
    UNLIMITED_DATA = "UnlimitedData"


@pulumi.type_token("azure-native_network_v20230201:network:ExpressRoutePortsEncapsulation")
class ExpressRoutePortsEncapsulation(builtins.str, Enum):
    """
    Encapsulation method on physical ports.
    """
    DOT1_Q = "Dot1Q"
    QIN_Q = "QinQ"


@pulumi.type_token("azure-native_network_v20230201:network:ExtendedLocationTypes")
class ExtendedLocationTypes(builtins.str, Enum):
    """
    The type of the extended location.
    """
    EDGE_ZONE = "EdgeZone"


@pulumi.type_token("azure-native_network_v20230201:network:FirewallPolicyFilterRuleCollectionActionType")
class FirewallPolicyFilterRuleCollectionActionType(builtins.str, Enum):
    """
    The type of action.
    """
    ALLOW = "Allow"
    DENY = "Deny"


@pulumi.type_token("azure-native_network_v20230201:network:FirewallPolicyIDPSQuerySortOrder")
class FirewallPolicyIDPSQuerySortOrder(builtins.str, Enum):
    """
    Describes if results should be in ascending/descending order
    """
    ASCENDING = "Ascending"
    DESCENDING = "Descending"


@pulumi.type_token("azure-native_network_v20230201:network:FirewallPolicyIntrusionDetectionProtocol")
class FirewallPolicyIntrusionDetectionProtocol(builtins.str, Enum):
    """
    The rule bypass protocol.
    """
    TCP = "TCP"
    UDP = "UDP"
    ICMP = "ICMP"
    ANY = "ANY"


@pulumi.type_token("azure-native_network_v20230201:network:FirewallPolicyIntrusionDetectionStateType")
class FirewallPolicyIntrusionDetectionStateType(builtins.str, Enum):
    """
    Intrusion detection general state.
    """
    OFF = "Off"
    ALERT = "Alert"
    DENY = "Deny"


@pulumi.type_token("azure-native_network_v20230201:network:FirewallPolicyNatRuleCollectionActionType")
class FirewallPolicyNatRuleCollectionActionType(builtins.str, Enum):
    """
    The type of action.
    """
    DNAT = "DNAT"


@pulumi.type_token("azure-native_network_v20230201:network:FirewallPolicyRuleApplicationProtocolType")
class FirewallPolicyRuleApplicationProtocolType(builtins.str, Enum):
    """
    Protocol type.
    """
    HTTP = "Http"
    HTTPS = "Https"


@pulumi.type_token("azure-native_network_v20230201:network:FirewallPolicyRuleCollectionType")
class FirewallPolicyRuleCollectionType(builtins.str, Enum):
    """
    The type of the rule collection.
    """
    FIREWALL_POLICY_NAT_RULE_COLLECTION = "FirewallPolicyNatRuleCollection"
    FIREWALL_POLICY_FILTER_RULE_COLLECTION = "FirewallPolicyFilterRuleCollection"


@pulumi.type_token("azure-native_network_v20230201:network:FirewallPolicyRuleNetworkProtocol")
class FirewallPolicyRuleNetworkProtocol(builtins.str, Enum):
    """
    The Network protocol of a Rule.
    """
    TCP = "TCP"
    UDP = "UDP"
    ANY = "Any"
    ICMP = "ICMP"


@pulumi.type_token("azure-native_network_v20230201:network:FirewallPolicyRuleType")
class FirewallPolicyRuleType(builtins.str, Enum):
    """
    Rule Type.
    """
    APPLICATION_RULE = "ApplicationRule"
    NETWORK_RULE = "NetworkRule"
    NAT_RULE = "NatRule"


@pulumi.type_token("azure-native_network_v20230201:network:FirewallPolicySkuTier")
class FirewallPolicySkuTier(builtins.str, Enum):
    """
    Tier of Firewall Policy.
    """
    STANDARD = "Standard"
    PREMIUM = "Premium"
    BASIC = "Basic"


@pulumi.type_token("azure-native_network_v20230201:network:FlowLogFormatType")
class FlowLogFormatType(builtins.str, Enum):
    """
    The file type of flow log.
    """
    JSON = "JSON"


@pulumi.type_token("azure-native_network_v20230201:network:GatewayLoadBalancerTunnelInterfaceType")
class GatewayLoadBalancerTunnelInterfaceType(builtins.str, Enum):
    """
    Traffic type of gateway load balancer tunnel interface.
    """
    NONE = "None"
    INTERNAL = "Internal"
    EXTERNAL = "External"


@pulumi.type_token("azure-native_network_v20230201:network:GatewayLoadBalancerTunnelProtocol")
class GatewayLoadBalancerTunnelProtocol(builtins.str, Enum):
    """
    Protocol of gateway load balancer tunnel interface.
    """
    NONE = "None"
    NATIVE = "Native"
    VXLAN = "VXLAN"


@pulumi.type_token("azure-native_network_v20230201:network:Geo")
class Geo(builtins.str, Enum):
    """
    The Geo for CIDR advertising. Should be an Geo code.
    """
    GLOBAL_ = "GLOBAL"
    AFRI = "AFRI"
    APAC = "APAC"
    EURO = "EURO"
    LATAM = "LATAM"
    NAM = "NAM"
    ME = "ME"
    OCEANIA = "OCEANIA"
    AQ = "AQ"


@pulumi.type_token("azure-native_network_v20230201:network:GroupConnectivity")
class GroupConnectivity(builtins.str, Enum):
    """
    Group connectivity type.
    """
    NONE = "None"
    DIRECTLY_CONNECTED = "DirectlyConnected"


@pulumi.type_token("azure-native_network_v20230201:network:HTTPConfigurationMethod")
class HTTPConfigurationMethod(builtins.str, Enum):
    """
    The HTTP method to use.
    """
    GET = "Get"
    POST = "Post"


@pulumi.type_token("azure-native_network_v20230201:network:HubRoutingPreference")
class HubRoutingPreference(builtins.str, Enum):
    """
    The hubRoutingPreference of this VirtualHub.
    """
    EXPRESS_ROUTE = "ExpressRoute"
    VPN_GATEWAY = "VpnGateway"
    AS_PATH = "ASPath"


@pulumi.type_token("azure-native_network_v20230201:network:IPAllocationMethod")
class IPAllocationMethod(builtins.str, Enum):
    """
    The private IP address allocation method.
    """
    STATIC = "Static"
    DYNAMIC = "Dynamic"


@pulumi.type_token("azure-native_network_v20230201:network:IPVersion")
class IPVersion(builtins.str, Enum):
    """
    Whether the specific IP configuration is IPv4 or IPv6. Default is IPv4.
    """
    I_PV4 = "IPv4"
    I_PV6 = "IPv6"


@pulumi.type_token("azure-native_network_v20230201:network:IkeEncryption")
class IkeEncryption(builtins.str, Enum):
    """
    The IKE encryption algorithm (IKE phase 2).
    """
    DES = "DES"
    DES3 = "DES3"
    AES128 = "AES128"
    AES192 = "AES192"
    AES256 = "AES256"
    GCMAES256 = "GCMAES256"
    GCMAES128 = "GCMAES128"


@pulumi.type_token("azure-native_network_v20230201:network:IkeIntegrity")
class IkeIntegrity(builtins.str, Enum):
    """
    The IKE integrity algorithm (IKE phase 2).
    """
    MD5 = "MD5"
    SHA1 = "SHA1"
    SHA256 = "SHA256"
    SHA384 = "SHA384"
    GCMAES256 = "GCMAES256"
    GCMAES128 = "GCMAES128"


@pulumi.type_token("azure-native_network_v20230201:network:IpAllocationType")
class IpAllocationType(builtins.str, Enum):
    """
    The type for the IpAllocation.
    """
    UNDEFINED = "Undefined"
    HYPERNET = "Hypernet"


@pulumi.type_token("azure-native_network_v20230201:network:IpsecEncryption")
class IpsecEncryption(builtins.str, Enum):
    """
    The IPSec encryption algorithm (IKE phase 1).
    """
    NONE = "None"
    DES = "DES"
    DES3 = "DES3"
    AES128 = "AES128"
    AES192 = "AES192"
    AES256 = "AES256"
    GCMAES128 = "GCMAES128"
    GCMAES192 = "GCMAES192"
    GCMAES256 = "GCMAES256"


@pulumi.type_token("azure-native_network_v20230201:network:IpsecIntegrity")
class IpsecIntegrity(builtins.str, Enum):
    """
    The IPSec integrity algorithm (IKE phase 1).
    """
    MD5 = "MD5"
    SHA1 = "SHA1"
    SHA256 = "SHA256"
    GCMAES128 = "GCMAES128"
    GCMAES192 = "GCMAES192"
    GCMAES256 = "GCMAES256"


@pulumi.type_token("azure-native_network_v20230201:network:IsGlobal")
class IsGlobal(builtins.str, Enum):
    """
    Flag if global mesh is supported.
    """
    FALSE = "False"
    TRUE = "True"


@pulumi.type_token("azure-native_network_v20230201:network:LoadBalancerBackendAddressAdminState")
class LoadBalancerBackendAddressAdminState(builtins.str, Enum):
    """
    A list of administrative states which once set can override health probe so that Load Balancer will always forward new connections to backend, or deny new connections and reset existing connections.
    """
    NONE = "None"
    UP = "Up"
    DOWN = "Down"


@pulumi.type_token("azure-native_network_v20230201:network:LoadBalancerOutboundRuleProtocol")
class LoadBalancerOutboundRuleProtocol(builtins.str, Enum):
    """
    The protocol for the outbound rule in load balancer.
    """
    TCP = "Tcp"
    UDP = "Udp"
    ALL = "All"


@pulumi.type_token("azure-native_network_v20230201:network:LoadBalancerSkuName")
class LoadBalancerSkuName(builtins.str, Enum):
    """
    Name of a load balancer SKU.
    """
    BASIC = "Basic"
    STANDARD = "Standard"
    GATEWAY = "Gateway"


@pulumi.type_token("azure-native_network_v20230201:network:LoadBalancerSkuTier")
class LoadBalancerSkuTier(builtins.str, Enum):
    """
    Tier of a load balancer SKU.
    """
    REGIONAL = "Regional"
    GLOBAL_ = "Global"


@pulumi.type_token("azure-native_network_v20230201:network:LoadDistribution")
class LoadDistribution(builtins.str, Enum):
    """
    The load distribution policy for this rule.
    """
    DEFAULT = "Default"
    SOURCE_IP = "SourceIP"
    SOURCE_IP_PROTOCOL = "SourceIPProtocol"


@pulumi.type_token("azure-native_network_v20230201:network:ManagedRuleEnabledState")
class ManagedRuleEnabledState(builtins.str, Enum):
    """
    The state of the managed rule. Defaults to Disabled if not specified.
    """
    DISABLED = "Disabled"
    ENABLED = "Enabled"


@pulumi.type_token("azure-native_network_v20230201:network:NatGatewaySkuName")
class NatGatewaySkuName(builtins.str, Enum):
    """
    Name of Nat Gateway SKU.
    """
    STANDARD = "Standard"


@pulumi.type_token("azure-native_network_v20230201:network:NetworkIntentPolicyBasedService")
class NetworkIntentPolicyBasedService(builtins.str, Enum):
    """
    Network intent policy based services.
    """
    NONE = "None"
    ALL = "All"
    ALLOW_RULES_ONLY = "AllowRulesOnly"


@pulumi.type_token("azure-native_network_v20230201:network:NetworkInterfaceAuxiliaryMode")
class NetworkInterfaceAuxiliaryMode(builtins.str, Enum):
    """
    Auxiliary mode of Network Interface resource.
    """
    NONE = "None"
    MAX_CONNECTIONS = "MaxConnections"
    FLOATING = "Floating"
    ACCELERATED_CONNECTIONS = "AcceleratedConnections"


@pulumi.type_token("azure-native_network_v20230201:network:NetworkInterfaceAuxiliarySku")
class NetworkInterfaceAuxiliarySku(builtins.str, Enum):
    """
    Auxiliary sku of Network Interface resource.
    """
    NONE = "None"
    A1 = "A1"
    A2 = "A2"
    A4 = "A4"
    A8 = "A8"


@pulumi.type_token("azure-native_network_v20230201:network:NetworkInterfaceMigrationPhase")
class NetworkInterfaceMigrationPhase(builtins.str, Enum):
    """
    Migration phase of Network Interface resource.
    """
    NONE = "None"
    PREPARE = "Prepare"
    COMMIT = "Commit"
    ABORT = "Abort"
    COMMITTED = "Committed"


@pulumi.type_token("azure-native_network_v20230201:network:NetworkInterfaceNicType")
class NetworkInterfaceNicType(builtins.str, Enum):
    """
    Type of Network Interface resource.
    """
    STANDARD = "Standard"
    ELASTIC = "Elastic"


@pulumi.type_token("azure-native_network_v20230201:network:NextStep")
class NextStep(builtins.str, Enum):
    """
    Next step after rule is evaluated. Current supported behaviors are 'Continue'(to next rule) and 'Terminate'.
    """
    UNKNOWN = "Unknown"
    CONTINUE_ = "Continue"
    TERMINATE = "Terminate"


@pulumi.type_token("azure-native_network_v20230201:network:OutputType")
class OutputType(builtins.str, Enum):
    """
    Connection monitor output destination type. Currently, only "Workspace" is supported.
    """
    WORKSPACE = "Workspace"


@pulumi.type_token("azure-native_network_v20230201:network:OwaspCrsExclusionEntryMatchVariable")
class OwaspCrsExclusionEntryMatchVariable(builtins.str, Enum):
    """
    The variable to be excluded.
    """
    REQUEST_HEADER_NAMES = "RequestHeaderNames"
    REQUEST_COOKIE_NAMES = "RequestCookieNames"
    REQUEST_ARG_NAMES = "RequestArgNames"
    REQUEST_HEADER_KEYS = "RequestHeaderKeys"
    REQUEST_HEADER_VALUES = "RequestHeaderValues"
    REQUEST_COOKIE_KEYS = "RequestCookieKeys"
    REQUEST_COOKIE_VALUES = "RequestCookieValues"
    REQUEST_ARG_KEYS = "RequestArgKeys"
    REQUEST_ARG_VALUES = "RequestArgValues"


@pulumi.type_token("azure-native_network_v20230201:network:OwaspCrsExclusionEntrySelectorMatchOperator")
class OwaspCrsExclusionEntrySelectorMatchOperator(builtins.str, Enum):
    """
    When matchVariable is a collection, operate on the selector to specify which elements in the collection this exclusion applies to.
    """
    EQUALS = "Equals"
    CONTAINS = "Contains"
    STARTS_WITH = "StartsWith"
    ENDS_WITH = "EndsWith"
    EQUALS_ANY = "EqualsAny"


@pulumi.type_token("azure-native_network_v20230201:network:PacketCaptureTargetType")
class PacketCaptureTargetType(builtins.str, Enum):
    """
    Target type of the resource provided.
    """
    AZURE_VM = "AzureVM"
    AZURE_VMSS = "AzureVMSS"


@pulumi.type_token("azure-native_network_v20230201:network:PcProtocol")
class PcProtocol(builtins.str, Enum):
    """
    Protocol to be filtered on.
    """
    TCP = "TCP"
    UDP = "UDP"
    ANY = "Any"


@pulumi.type_token("azure-native_network_v20230201:network:PfsGroup")
class PfsGroup(builtins.str, Enum):
    """
    The Pfs Group used in IKE Phase 2 for new child SA.
    """
    NONE = "None"
    PFS1 = "PFS1"
    PFS2 = "PFS2"
    PFS2048 = "PFS2048"
    ECP256 = "ECP256"
    ECP384 = "ECP384"
    PFS24 = "PFS24"
    PFS14 = "PFS14"
    PFSMM = "PFSMM"


@pulumi.type_token("azure-native_network_v20230201:network:PreferredIPVersion")
class PreferredIPVersion(builtins.str, Enum):
    """
    The preferred IP version to use in test evaluation. The connection monitor may choose to use a different version depending on other parameters.
    """
    I_PV4 = "IPv4"
    I_PV6 = "IPv6"


@pulumi.type_token("azure-native_network_v20230201:network:PreferredRoutingGateway")
class PreferredRoutingGateway(builtins.str, Enum):
    """
    The preferred gateway to route on-prem traffic
    """
    EXPRESS_ROUTE = "ExpressRoute"
    VPN_GATEWAY = "VpnGateway"
    NONE = "None"


@pulumi.type_token("azure-native_network_v20230201:network:ProbeProtocol")
class ProbeProtocol(builtins.str, Enum):
    """
    The protocol of the end point. If 'Tcp' is specified, a received ACK is required for the probe to be successful. If 'Http' or 'Https' is specified, a 200 OK response from the specifies URI is required for the probe to be successful.
    """
    HTTP = "Http"
    TCP = "Tcp"
    HTTPS = "Https"


@pulumi.type_token("azure-native_network_v20230201:network:ProtocolType")
class ProtocolType(builtins.str, Enum):
    """
    RNM supported protocol types.
    """
    DO_NOT_USE = "DoNotUse"
    ICMP = "Icmp"
    TCP = "Tcp"
    UDP = "Udp"
    GRE = "Gre"
    ESP = "Esp"
    AH = "Ah"
    VXLAN = "Vxlan"
    ALL = "All"


@pulumi.type_token("azure-native_network_v20230201:network:PublicIPAddressMigrationPhase")
class PublicIPAddressMigrationPhase(builtins.str, Enum):
    """
    Migration phase of Public IP Address.
    """
    NONE = "None"
    PREPARE = "Prepare"
    COMMIT = "Commit"
    ABORT = "Abort"
    COMMITTED = "Committed"


@pulumi.type_token("azure-native_network_v20230201:network:PublicIPAddressSkuName")
class PublicIPAddressSkuName(builtins.str, Enum):
    """
    Name of a public IP address SKU.
    """
    BASIC = "Basic"
    STANDARD = "Standard"


@pulumi.type_token("azure-native_network_v20230201:network:PublicIPAddressSkuTier")
class PublicIPAddressSkuTier(builtins.str, Enum):
    """
    Tier of a public IP address SKU.
    """
    REGIONAL = "Regional"
    GLOBAL_ = "Global"


@pulumi.type_token("azure-native_network_v20230201:network:PublicIPPrefixSkuName")
class PublicIPPrefixSkuName(builtins.str, Enum):
    """
    Name of a public IP prefix SKU.
    """
    STANDARD = "Standard"


@pulumi.type_token("azure-native_network_v20230201:network:PublicIPPrefixSkuTier")
class PublicIPPrefixSkuTier(builtins.str, Enum):
    """
    Tier of a public IP prefix SKU.
    """
    REGIONAL = "Regional"
    GLOBAL_ = "Global"


@pulumi.type_token("azure-native_network_v20230201:network:PublicIpAddressDnsSettingsDomainNameLabelScope")
class PublicIpAddressDnsSettingsDomainNameLabelScope(builtins.str, Enum):
    """
    The domain name label scope. If a domain name label and a domain name label scope are specified, an A DNS record is created for the public IP in the Microsoft Azure DNS system with a hashed value includes in FQDN.
    """
    TENANT_REUSE = "TenantReuse"
    SUBSCRIPTION_REUSE = "SubscriptionReuse"
    RESOURCE_GROUP_REUSE = "ResourceGroupReuse"
    NO_REUSE = "NoReuse"


@pulumi.type_token("azure-native_network_v20230201:network:ResourceIdentityType")
class ResourceIdentityType(builtins.str, Enum):
    """
    The type of identity used for the resource. The type 'SystemAssigned, UserAssigned' includes both an implicitly created identity and a set of user assigned identities. The type 'None' will remove any identities from the virtual machine.
    """
    SYSTEM_ASSIGNED = "SystemAssigned"
    USER_ASSIGNED = "UserAssigned"
    SYSTEM_ASSIGNED_USER_ASSIGNED = "SystemAssigned, UserAssigned"
    NONE = "None"


@pulumi.type_token("azure-native_network_v20230201:network:RouteFilterRuleType")
class RouteFilterRuleType(builtins.str, Enum):
    """
    The rule type of the rule.
    """
    COMMUNITY = "Community"


@pulumi.type_token("azure-native_network_v20230201:network:RouteMapActionType")
class RouteMapActionType(builtins.str, Enum):
    """
    Type of action to be taken. Supported types are 'Remove', 'Add', 'Replace', and 'Drop.'
    """
    UNKNOWN = "Unknown"
    REMOVE = "Remove"
    ADD = "Add"
    REPLACE = "Replace"
    DROP = "Drop"


@pulumi.type_token("azure-native_network_v20230201:network:RouteMapMatchCondition")
class RouteMapMatchCondition(builtins.str, Enum):
    """
    Match condition to apply RouteMap rules.
    """
    UNKNOWN = "Unknown"
    CONTAINS = "Contains"
    EQUALS = "Equals"
    NOT_CONTAINS = "NotContains"
    NOT_EQUALS = "NotEquals"


@pulumi.type_token("azure-native_network_v20230201:network:RouteNextHopType")
class RouteNextHopType(builtins.str, Enum):
    """
    The type of Azure hop the packet should be sent to.
    """
    VIRTUAL_NETWORK_GATEWAY = "VirtualNetworkGateway"
    VNET_LOCAL = "VnetLocal"
    INTERNET = "Internet"
    VIRTUAL_APPLIANCE = "VirtualAppliance"
    NONE = "None"


@pulumi.type_token("azure-native_network_v20230201:network:ScrubbingRuleEntryMatchOperator")
class ScrubbingRuleEntryMatchOperator(builtins.str, Enum):
    """
    When matchVariable is a collection, operate on the selector to specify which elements in the collection this rule applies to.
    """
    EQUALS = "Equals"
    EQUALS_ANY = "EqualsAny"


@pulumi.type_token("azure-native_network_v20230201:network:ScrubbingRuleEntryMatchVariable")
class ScrubbingRuleEntryMatchVariable(builtins.str, Enum):
    """
    The variable to be scrubbed from the logs.
    """
    REQUEST_HEADER_NAMES = "RequestHeaderNames"
    REQUEST_COOKIE_NAMES = "RequestCookieNames"
    REQUEST_ARG_NAMES = "RequestArgNames"
    REQUEST_POST_ARG_NAMES = "RequestPostArgNames"
    REQUEST_JSON_ARG_NAMES = "RequestJSONArgNames"
    REQUEST_IP_ADDRESS = "RequestIPAddress"


@pulumi.type_token("azure-native_network_v20230201:network:ScrubbingRuleEntryState")
class ScrubbingRuleEntryState(builtins.str, Enum):
    """
    Defines the state of log scrubbing rule. Default value is Enabled.
    """
    ENABLED = "Enabled"
    DISABLED = "Disabled"


@pulumi.type_token("azure-native_network_v20230201:network:SecurityConfigurationRuleAccess")
class SecurityConfigurationRuleAccess(builtins.str, Enum):
    """
    Indicates the access allowed for this particular rule
    """
    ALLOW = "Allow"
    DENY = "Deny"
    ALWAYS_ALLOW = "AlwaysAllow"


@pulumi.type_token("azure-native_network_v20230201:network:SecurityConfigurationRuleDirection")
class SecurityConfigurationRuleDirection(builtins.str, Enum):
    """
    Indicates if the traffic matched against the rule in inbound or outbound.
    """
    INBOUND = "Inbound"
    OUTBOUND = "Outbound"


@pulumi.type_token("azure-native_network_v20230201:network:SecurityConfigurationRuleProtocol")
class SecurityConfigurationRuleProtocol(builtins.str, Enum):
    """
    Network protocol this rule applies to.
    """
    TCP = "Tcp"
    UDP = "Udp"
    ICMP = "Icmp"
    ESP = "Esp"
    ANY = "Any"
    AH = "Ah"


@pulumi.type_token("azure-native_network_v20230201:network:SecurityProviderName")
class SecurityProviderName(builtins.str, Enum):
    """
    The security provider name.
    """
    Z_SCALER = "ZScaler"
    I_BOSS = "IBoss"
    CHECKPOINT = "Checkpoint"


@pulumi.type_token("azure-native_network_v20230201:network:SecurityRuleAccess")
class SecurityRuleAccess(builtins.str, Enum):
    """
    The network traffic is allowed or denied.
    """
    ALLOW = "Allow"
    DENY = "Deny"


@pulumi.type_token("azure-native_network_v20230201:network:SecurityRuleDirection")
class SecurityRuleDirection(builtins.str, Enum):
    """
    The direction of the rule. The direction specifies if rule will be evaluated on incoming or outgoing traffic.
    """
    INBOUND = "Inbound"
    OUTBOUND = "Outbound"


@pulumi.type_token("azure-native_network_v20230201:network:SecurityRuleProtocol")
class SecurityRuleProtocol(builtins.str, Enum):
    """
    Network protocol this rule applies to.
    """
    TCP = "Tcp"
    UDP = "Udp"
    ICMP = "Icmp"
    ESP = "Esp"
    ASTERISK = "*"
    AH = "Ah"


@pulumi.type_token("azure-native_network_v20230201:network:ServiceProviderProvisioningState")
class ServiceProviderProvisioningState(builtins.str, Enum):
    """
    The ServiceProviderProvisioningState state of the resource.
    """
    NOT_PROVISIONED = "NotProvisioned"
    PROVISIONING = "Provisioning"
    PROVISIONED = "Provisioned"
    DEPROVISIONING = "Deprovisioning"


@pulumi.type_token("azure-native_network_v20230201:network:TransportProtocol")
class TransportProtocol(builtins.str, Enum):
    """
    The reference to the transport protocol used by the load balancing rule.
    """
    UDP = "Udp"
    TCP = "Tcp"
    ALL = "All"


@pulumi.type_token("azure-native_network_v20230201:network:UseHubGateway")
class UseHubGateway(builtins.str, Enum):
    """
    Flag if need to use hub gateway.
    """
    FALSE = "False"
    TRUE = "True"


@pulumi.type_token("azure-native_network_v20230201:network:VirtualNetworkEncryptionEnforcement")
class VirtualNetworkEncryptionEnforcement(builtins.str, Enum):
    """
    If the encrypted VNet allows VM that does not support encryption
    """
    DROP_UNENCRYPTED = "DropUnencrypted"
    ALLOW_UNENCRYPTED = "AllowUnencrypted"


@pulumi.type_token("azure-native_network_v20230201:network:VirtualNetworkGatewayConnectionMode")
class VirtualNetworkGatewayConnectionMode(builtins.str, Enum):
    """
    The connection mode for this connection.
    """
    DEFAULT = "Default"
    RESPONDER_ONLY = "ResponderOnly"
    INITIATOR_ONLY = "InitiatorOnly"


@pulumi.type_token("azure-native_network_v20230201:network:VirtualNetworkGatewayConnectionProtocol")
class VirtualNetworkGatewayConnectionProtocol(builtins.str, Enum):
    """
    Connection protocol used for this connection.
    """
    IK_EV2 = "IKEv2"
    IK_EV1 = "IKEv1"


@pulumi.type_token("azure-native_network_v20230201:network:VirtualNetworkGatewayConnectionType")
class VirtualNetworkGatewayConnectionType(builtins.str, Enum):
    """
    Gateway connection type.
    """
    IPSEC = "IPsec"
    VNET2_VNET = "Vnet2Vnet"
    EXPRESS_ROUTE = "ExpressRoute"
    VPN_CLIENT = "VPNClient"


@pulumi.type_token("azure-native_network_v20230201:network:VirtualNetworkGatewaySkuName")
class VirtualNetworkGatewaySkuName(builtins.str, Enum):
    """
    Gateway SKU name.
    """
    BASIC = "Basic"
    HIGH_PERFORMANCE = "HighPerformance"
    STANDARD = "Standard"
    ULTRA_PERFORMANCE = "UltraPerformance"
    VPN_GW1 = "VpnGw1"
    VPN_GW2 = "VpnGw2"
    VPN_GW3 = "VpnGw3"
    VPN_GW4 = "VpnGw4"
    VPN_GW5 = "VpnGw5"
    VPN_GW1_AZ = "VpnGw1AZ"
    VPN_GW2_AZ = "VpnGw2AZ"
    VPN_GW3_AZ = "VpnGw3AZ"
    VPN_GW4_AZ = "VpnGw4AZ"
    VPN_GW5_AZ = "VpnGw5AZ"
    ER_GW1_AZ = "ErGw1AZ"
    ER_GW2_AZ = "ErGw2AZ"
    ER_GW3_AZ = "ErGw3AZ"


@pulumi.type_token("azure-native_network_v20230201:network:VirtualNetworkGatewaySkuTier")
class VirtualNetworkGatewaySkuTier(builtins.str, Enum):
    """
    Gateway SKU tier.
    """
    BASIC = "Basic"
    HIGH_PERFORMANCE = "HighPerformance"
    STANDARD = "Standard"
    ULTRA_PERFORMANCE = "UltraPerformance"
    VPN_GW1 = "VpnGw1"
    VPN_GW2 = "VpnGw2"
    VPN_GW3 = "VpnGw3"
    VPN_GW4 = "VpnGw4"
    VPN_GW5 = "VpnGw5"
    VPN_GW1_AZ = "VpnGw1AZ"
    VPN_GW2_AZ = "VpnGw2AZ"
    VPN_GW3_AZ = "VpnGw3AZ"
    VPN_GW4_AZ = "VpnGw4AZ"
    VPN_GW5_AZ = "VpnGw5AZ"
    ER_GW1_AZ = "ErGw1AZ"
    ER_GW2_AZ = "ErGw2AZ"
    ER_GW3_AZ = "ErGw3AZ"


@pulumi.type_token("azure-native_network_v20230201:network:VirtualNetworkGatewayType")
class VirtualNetworkGatewayType(builtins.str, Enum):
    """
    The type of this virtual network gateway.
    """
    VPN = "Vpn"
    EXPRESS_ROUTE = "ExpressRoute"
    LOCAL_GATEWAY = "LocalGateway"


@pulumi.type_token("azure-native_network_v20230201:network:VirtualNetworkPeeringLevel")
class VirtualNetworkPeeringLevel(builtins.str, Enum):
    """
    The peering sync status of the virtual network peering.
    """
    FULLY_IN_SYNC = "FullyInSync"
    REMOTE_NOT_IN_SYNC = "RemoteNotInSync"
    LOCAL_NOT_IN_SYNC = "LocalNotInSync"
    LOCAL_AND_REMOTE_NOT_IN_SYNC = "LocalAndRemoteNotInSync"


@pulumi.type_token("azure-native_network_v20230201:network:VirtualNetworkPeeringState")
class VirtualNetworkPeeringState(builtins.str, Enum):
    """
    The status of the virtual network peering.
    """
    INITIATED = "Initiated"
    CONNECTED = "Connected"
    DISCONNECTED = "Disconnected"


@pulumi.type_token("azure-native_network_v20230201:network:VirtualNetworkPrivateEndpointNetworkPolicies")
class VirtualNetworkPrivateEndpointNetworkPolicies(builtins.str, Enum):
    """
    Enable or Disable apply network policies on private end point in the subnet.
    """
    ENABLED = "Enabled"
    DISABLED = "Disabled"


@pulumi.type_token("azure-native_network_v20230201:network:VirtualNetworkPrivateLinkServiceNetworkPolicies")
class VirtualNetworkPrivateLinkServiceNetworkPolicies(builtins.str, Enum):
    """
    Enable or Disable apply network policies on private link service in the subnet.
    """
    ENABLED = "Enabled"
    DISABLED = "Disabled"


@pulumi.type_token("azure-native_network_v20230201:network:VnetLocalRouteOverrideCriteria")
class VnetLocalRouteOverrideCriteria(builtins.str, Enum):
    """
    Parameter determining whether NVA in spoke vnet is bypassed for traffic with destination in spoke.
    """
    CONTAINS = "Contains"
    EQUAL = "Equal"


@pulumi.type_token("azure-native_network_v20230201:network:VpnAuthenticationType")
class VpnAuthenticationType(builtins.str, Enum):
    """
    VPN authentication types enabled for the VpnServerConfiguration.
    """
    CERTIFICATE = "Certificate"
    RADIUS = "Radius"
    AAD = "AAD"


@pulumi.type_token("azure-native_network_v20230201:network:VpnClientProtocol")
class VpnClientProtocol(builtins.str, Enum):
    """
    VPN client protocol enabled for the virtual network gateway.
    """
    IKE_V2 = "IkeV2"
    SSTP = "SSTP"
    OPEN_VPN = "OpenVPN"


@pulumi.type_token("azure-native_network_v20230201:network:VpnGatewayGeneration")
class VpnGatewayGeneration(builtins.str, Enum):
    """
    The generation for this VirtualNetworkGateway. Must be None if gatewayType is not VPN.
    """
    NONE = "None"
    GENERATION1 = "Generation1"
    GENERATION2 = "Generation2"


@pulumi.type_token("azure-native_network_v20230201:network:VpnGatewayTunnelingProtocol")
class VpnGatewayTunnelingProtocol(builtins.str, Enum):
    """
    VPN protocol enabled for the VpnServerConfiguration.
    """
    IKE_V2 = "IkeV2"
    OPEN_VPN = "OpenVPN"


@pulumi.type_token("azure-native_network_v20230201:network:VpnLinkConnectionMode")
class VpnLinkConnectionMode(builtins.str, Enum):
    """
    Vpn link connection mode.
    """
    DEFAULT = "Default"
    RESPONDER_ONLY = "ResponderOnly"
    INITIATOR_ONLY = "InitiatorOnly"


@pulumi.type_token("azure-native_network_v20230201:network:VpnNatRuleMode")
class VpnNatRuleMode(builtins.str, Enum):
    """
    The Source NAT direction of a VPN NAT.
    """
    EGRESS_SNAT = "EgressSnat"
    INGRESS_SNAT = "IngressSnat"


@pulumi.type_token("azure-native_network_v20230201:network:VpnNatRuleType")
class VpnNatRuleType(builtins.str, Enum):
    """
    The type of NAT rule for VPN NAT.
    """
    STATIC = "Static"
    DYNAMIC = "Dynamic"


@pulumi.type_token("azure-native_network_v20230201:network:VpnPolicyMemberAttributeType")
class VpnPolicyMemberAttributeType(builtins.str, Enum):
    """
    The Vpn Policy member attribute type.
    """
    CERTIFICATE_GROUP_ID = "CertificateGroupId"
    AAD_GROUP_ID = "AADGroupId"
    RADIUS_AZURE_GROUP_ID = "RadiusAzureGroupId"


@pulumi.type_token("azure-native_network_v20230201:network:VpnType")
class VpnType(builtins.str, Enum):
    """
    The type of this virtual network gateway.
    """
    POLICY_BASED = "PolicyBased"
    ROUTE_BASED = "RouteBased"


@pulumi.type_token("azure-native_network_v20230201:network:WebApplicationFirewallAction")
class WebApplicationFirewallAction(builtins.str, Enum):
    """
    Type of Actions.
    """
    ALLOW = "Allow"
    BLOCK = "Block"
    LOG = "Log"


@pulumi.type_token("azure-native_network_v20230201:network:WebApplicationFirewallEnabledState")
class WebApplicationFirewallEnabledState(builtins.str, Enum):
    """
    The state of the policy.
    """
    DISABLED = "Disabled"
    ENABLED = "Enabled"


@pulumi.type_token("azure-native_network_v20230201:network:WebApplicationFirewallMatchVariable")
class WebApplicationFirewallMatchVariable(builtins.str, Enum):
    """
    Match Variable.
    """
    REMOTE_ADDR = "RemoteAddr"
    REQUEST_METHOD = "RequestMethod"
    QUERY_STRING = "QueryString"
    POST_ARGS = "PostArgs"
    REQUEST_URI = "RequestUri"
    REQUEST_HEADERS = "RequestHeaders"
    REQUEST_BODY = "RequestBody"
    REQUEST_COOKIES = "RequestCookies"


@pulumi.type_token("azure-native_network_v20230201:network:WebApplicationFirewallMode")
class WebApplicationFirewallMode(builtins.str, Enum):
    """
    The mode of the policy.
    """
    PREVENTION = "Prevention"
    DETECTION = "Detection"


@pulumi.type_token("azure-native_network_v20230201:network:WebApplicationFirewallOperator")
class WebApplicationFirewallOperator(builtins.str, Enum):
    """
    The operator to be matched.
    """
    IP_MATCH = "IPMatch"
    EQUAL = "Equal"
    CONTAINS = "Contains"
    LESS_THAN = "LessThan"
    GREATER_THAN = "GreaterThan"
    LESS_THAN_OR_EQUAL = "LessThanOrEqual"
    GREATER_THAN_OR_EQUAL = "GreaterThanOrEqual"
    BEGINS_WITH = "BeginsWith"
    ENDS_WITH = "EndsWith"
    REGEX = "Regex"
    GEO_MATCH = "GeoMatch"
    ANY = "Any"


@pulumi.type_token("azure-native_network_v20230201:network:WebApplicationFirewallRuleType")
class WebApplicationFirewallRuleType(builtins.str, Enum):
    """
    The rule type.
    """
    MATCH_RULE = "MatchRule"
    RATE_LIMIT_RULE = "RateLimitRule"
    INVALID = "Invalid"


@pulumi.type_token("azure-native_network_v20230201:network:WebApplicationFirewallScrubbingState")
class WebApplicationFirewallScrubbingState(builtins.str, Enum):
    """
    State of the log scrubbing config. Default value is Enabled.
    """
    DISABLED = "Disabled"
    ENABLED = "Enabled"


@pulumi.type_token("azure-native_network_v20230201:network:WebApplicationFirewallState")
class WebApplicationFirewallState(builtins.str, Enum):
    """
    Describes if the custom rule is in enabled or disabled state. Defaults to Enabled if not specified.
    """
    DISABLED = "Disabled"
    ENABLED = "Enabled"


@pulumi.type_token("azure-native_network_v20230201:network:WebApplicationFirewallTransform")
class WebApplicationFirewallTransform(builtins.str, Enum):
    """
    Transforms applied before matching.
    """
    UPPERCASE = "Uppercase"
    LOWERCASE = "Lowercase"
    TRIM = "Trim"
    URL_DECODE = "UrlDecode"
    URL_ENCODE = "UrlEncode"
    REMOVE_NULLS = "RemoveNulls"
    HTML_ENTITY_DECODE = "HtmlEntityDecode"
